version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
    labels:
      - dependencies
      - breaking
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
    groups:
      minor-patch-updates:
        applies-to: version-updates
        update-types:
          - minor
          - patch
      security-updates:
        applies-to: security-updates
        update-types:
          - minor
          - patch

  - package-ecosystem: nuget
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
    labels:
      - dependencies
      - breaking
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: daily
    groups:
      minor-patch-updates:
        applies-to: version-updates
        update-types:
          - minor
          - patch
      security-updates:
        applies-to: security-updates
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
